name: Python Package - Multi-Version Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install flake8 pytest pillow==9.4.0  # Pin compatible Pillow

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Tests with pytest (Retry on Failure)
        run: |
          pytest || (echo "Retrying in 5 seconds..." && sleep 5 && pytest)
